export const MS_IN_SECOND = 1000;
export const SECONDS_IN_MINUTE = 60;
export const MINUTES_IN_HOUR = 60;
export const HOURS_IN_DAY = 24;

export const REFRESH_TOKEN_MAX_AGE_IN_DAYS = 30;
export const ACCESS_TOKEN_IN_MINUTES = 15;

export const DEFAULTS_FOR_COOKIES_MAX_AGE = {
  REFRESH_TOKEN:
    REFRESH_TOKEN_MAX_AGE_IN_DAYS *
    HOURS_IN_DAY *
    MINUTES_IN_HOUR *
    SECONDS_IN_MINUTE *
    MS_IN_SECOND,
  ACCESS_TOKEN: ACCESS_TOKEN_IN_MINUTES * MS_IN_SECOND,
};
